2024-06-11 17:00:41,897 INFO    StreamThr :5200 [internal.py:wandb_internal():85] W&B internal server running at pid: 5200, started at: 2024-06-11 17:00:41.896356
2024-06-11 17:00:41,898 DEBUG   HandlerThread:5200 [handler.py:handle_request():158] handle_request: status
2024-06-11 17:00:41,901 INFO    WriterThread:5200 [datastore.py:open_for_write():87] open: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240611_170041-wdbla3eu/run-wdbla3eu.wandb
2024-06-11 17:00:41,901 DEBUG   SenderThread:5200 [sender.py:send():379] send: header
2024-06-11 17:00:41,928 DEBUG   SenderThread:5200 [sender.py:send():379] send: run
2024-06-11 17:00:42,477 INFO    SenderThread:5200 [dir_watcher.py:__init__():211] watching files in: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240611_170041-wdbla3eu/files
2024-06-11 17:00:42,477 INFO    SenderThread:5200 [sender.py:_start_run_threads():1188] run started: wdbla3eu with start time 1718114441.897488
2024-06-11 17:00:42,487 DEBUG   HandlerThread:5200 [handler.py:handle_request():158] handle_request: check_version
2024-06-11 17:00:42,487 DEBUG   SenderThread:5200 [sender.py:send_request():406] send_request: check_version
2024-06-11 17:00:43,798 DEBUG   HandlerThread:5200 [handler.py:handle_request():158] handle_request: run_start
2024-06-11 17:00:43,799 DEBUG   HandlerThread:5200 [system_info.py:__init__():26] System info init
2024-06-11 17:00:43,799 DEBUG   HandlerThread:5200 [system_info.py:__init__():41] System info init done
2024-06-11 17:00:43,800 INFO    HandlerThread:5200 [system_monitor.py:start():194] Starting system monitor
2024-06-11 17:00:43,800 INFO    SystemMonitor:5200 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-06-11 17:00:43,800 INFO    HandlerThread:5200 [system_monitor.py:probe():214] Collecting system info
2024-06-11 17:00:43,800 INFO    SystemMonitor:5200 [interfaces.py:start():188] Started cpu monitoring
2024-06-11 17:00:43,802 INFO    SystemMonitor:5200 [interfaces.py:start():188] Started disk monitoring
2024-06-11 17:00:43,807 INFO    SystemMonitor:5200 [interfaces.py:start():188] Started gpuapple monitoring
2024-06-11 17:00:43,810 INFO    SystemMonitor:5200 [interfaces.py:start():188] Started memory monitoring
2024-06-11 17:00:43,811 INFO    SystemMonitor:5200 [interfaces.py:start():188] Started network monitoring
2024-06-11 17:00:44,021 ERROR   gpuapple  :5200 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-11 17:00:44,096 ERROR   HandlerThread:5200 [gpu_apple.py:probe():176] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 164, in probe
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-11 17:00:44,096 DEBUG   HandlerThread:5200 [system_info.py:probe():152] Probing system
2024-06-11 17:00:44,099 DEBUG   HandlerThread:5200 [system_info.py:_probe_git():137] Probing git
2024-06-11 17:00:44,111 DEBUG   HandlerThread:5200 [system_info.py:_probe_git():145] Probing git done
2024-06-11 17:00:44,111 DEBUG   HandlerThread:5200 [system_info.py:probe():200] Probing system done
2024-06-11 17:00:44,111 DEBUG   HandlerThread:5200 [system_monitor.py:probe():223] {'os': 'macOS-14.5-arm64-arm-64bit', 'python': '3.8.18', 'heartbeatAt': '2024-06-11T14:00:44.096954', 'startedAt': '2024-06-11T14:00:41.888365', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/two_d_train.py', 'codePathLocal': 'two_d_train.py', 'codePath': 'two_d_train.py', 'git': {'remote': 'https://github.com/idanv87/deep_attention.git', 'commit': '80cc1b3a0aaf87fd0f522e86c3be646c767e6aac'}, 'email': 'idanv@campus.technion.ac.il', 'root': '/Users/idanversano/Documents/project_geo_deeponet/deep_attention/src', 'host': 'idans-MacBook-Air.local', 'username': 'idanversano', 'executable': '/Users/idanversano/miniforge3/envs/torch_env/bin/python', 'cpu_count': 8, 'cpu_count_logical': 8, 'cpu_freq': {'current': 3204, 'min': 600, 'max': 3204}, 'cpu_freq_per_core': [{'current': 3204, 'min': 600, 'max': 3204}], 'disk': {'/': {'total': 228.27386474609375, 'used': 9.562911987304688}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 8.0}}
2024-06-11 17:00:44,111 INFO    HandlerThread:5200 [system_monitor.py:probe():224] Finished collecting system info
2024-06-11 17:00:44,111 INFO    HandlerThread:5200 [system_monitor.py:probe():227] Publishing system info
2024-06-11 17:00:44,112 DEBUG   HandlerThread:5200 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2024-06-11 17:00:44,115 ERROR   HandlerThread:5200 [system_info.py:_save_conda():223] Error saving conda packages: [Errno 2] No such file or directory: 'conda'
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/system_info.py", line 216, in _save_conda
    subprocess.call(
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'conda'
2024-06-11 17:00:44,115 DEBUG   HandlerThread:5200 [system_info.py:_save_conda():224] Saving conda packages done
2024-06-11 17:00:44,115 INFO    HandlerThread:5200 [system_monitor.py:probe():229] Finished publishing system info
2024-06-11 17:00:44,119 DEBUG   SenderThread:5200 [sender.py:send():379] send: files
2024-06-11 17:00:44,119 INFO    SenderThread:5200 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2024-06-11 17:00:44,202 DEBUG   HandlerThread:5200 [handler.py:handle_request():158] handle_request: python_packages
2024-06-11 17:00:44,202 DEBUG   SenderThread:5200 [sender.py:send_request():406] send_request: python_packages
2024-06-11 17:00:44,203 DEBUG   SenderThread:5200 [sender.py:send():379] send: telemetry
2024-06-11 17:00:44,203 DEBUG   HandlerThread:5200 [handler.py:handle_request():158] handle_request: stop_status
2024-06-11 17:00:44,203 DEBUG   HandlerThread:5200 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:00:44,203 DEBUG   SenderThread:5200 [sender.py:send_request():406] send_request: stop_status
2024-06-11 17:00:44,488 INFO    Thread-12 :5200 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240611_170041-wdbla3eu/files/wandb-metadata.json
2024-06-11 17:00:44,489 INFO    Thread-12 :5200 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240611_170041-wdbla3eu/files/output.log
2024-06-11 17:00:44,489 INFO    Thread-12 :5200 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240611_170041-wdbla3eu/files/conda-environment.yaml
2024-06-11 17:00:44,489 INFO    Thread-12 :5200 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240611_170041-wdbla3eu/files/requirements.txt
2024-06-11 17:00:45,016 INFO    wandb-upload_0:5200 [upload_job.py:push():130] Uploaded file /var/folders/tf/xl2_rn496w36wzs_pk18q7vr0000gn/T/tmpbuhivyxcwandb/2f1jqgq2-wandb-metadata.json
2024-06-11 17:00:45,207 DEBUG   HandlerThread:5200 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:00:46,163 ERROR   gpuapple  :5200 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-11 17:00:46,209 DEBUG   HandlerThread:5200 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:00:46,500 INFO    Thread-12 :5200 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240611_170041-wdbla3eu/files/output.log
2024-06-11 17:00:46,934 DEBUG   HandlerThread:5200 [handler.py:handle_request():158] handle_request: status_report
2024-06-11 17:00:47,211 DEBUG   HandlerThread:5200 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:00:48,214 DEBUG   HandlerThread:5200 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:00:48,325 ERROR   gpuapple  :5200 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-11 17:00:48,508 INFO    Thread-12 :5200 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240611_170041-wdbla3eu/files/output.log
2024-06-11 17:00:49,213 DEBUG   HandlerThread:5200 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:00:49,815 INFO    cpu       :5200 [interfaces.py:monitor():138] Process cpu has exited.
2024-06-11 17:00:49,816 DEBUG   SystemMonitor:5200 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-06-11 17:00:49,817 DEBUG   SystemMonitor:5200 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-06-11 17:00:49,817 DEBUG   SystemMonitor:5200 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-06-11 17:00:49,818 DEBUG   SenderThread:5200 [sender.py:send():379] send: telemetry
2024-06-11 17:00:49,819 DEBUG   SenderThread:5200 [sender.py:send():379] send: stats
2024-06-11 17:00:50,519 INFO    Thread-12 :5200 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240611_170041-wdbla3eu/files/output.log
2024-06-11 17:00:50,820 INFO    MainThread:5200 [internal.py:handle_exit():75] Internal process exited
