2024-06-11 17:17:37,254 INFO    StreamThr :5572 [internal.py:wandb_internal():85] W&B internal server running at pid: 5572, started at: 2024-06-11 17:17:37.252814
2024-06-11 17:17:37,255 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: status
2024-06-11 17:17:37,257 INFO    WriterThread:5572 [datastore.py:open_for_write():87] open: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240611_171737-jzp58xbj/run-jzp58xbj.wandb
2024-06-11 17:17:37,258 DEBUG   SenderThread:5572 [sender.py:send():379] send: header
2024-06-11 17:17:37,279 DEBUG   SenderThread:5572 [sender.py:send():379] send: run
2024-06-11 17:17:37,898 INFO    SenderThread:5572 [dir_watcher.py:__init__():211] watching files in: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240611_171737-jzp58xbj/files
2024-06-11 17:17:37,898 INFO    SenderThread:5572 [sender.py:_start_run_threads():1188] run started: jzp58xbj with start time 1718115457.254058
2024-06-11 17:17:37,912 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: check_version
2024-06-11 17:17:37,912 DEBUG   SenderThread:5572 [sender.py:send_request():406] send_request: check_version
2024-06-11 17:17:38,248 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: run_start
2024-06-11 17:17:38,249 DEBUG   HandlerThread:5572 [system_info.py:__init__():26] System info init
2024-06-11 17:17:38,250 DEBUG   HandlerThread:5572 [system_info.py:__init__():41] System info init done
2024-06-11 17:17:38,250 INFO    HandlerThread:5572 [system_monitor.py:start():194] Starting system monitor
2024-06-11 17:17:38,250 INFO    SystemMonitor:5572 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-06-11 17:17:38,250 INFO    HandlerThread:5572 [system_monitor.py:probe():214] Collecting system info
2024-06-11 17:17:38,255 INFO    SystemMonitor:5572 [interfaces.py:start():188] Started cpu monitoring
2024-06-11 17:17:38,258 INFO    SystemMonitor:5572 [interfaces.py:start():188] Started disk monitoring
2024-06-11 17:17:38,259 INFO    SystemMonitor:5572 [interfaces.py:start():188] Started gpuapple monitoring
2024-06-11 17:17:38,262 INFO    SystemMonitor:5572 [interfaces.py:start():188] Started memory monitoring
2024-06-11 17:17:38,263 INFO    SystemMonitor:5572 [interfaces.py:start():188] Started network monitoring
2024-06-11 17:17:38,414 ERROR   HandlerThread:5572 [gpu_apple.py:probe():176] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 164, in probe
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-11 17:17:38,416 DEBUG   HandlerThread:5572 [system_info.py:probe():152] Probing system
2024-06-11 17:17:38,419 DEBUG   HandlerThread:5572 [system_info.py:_probe_git():137] Probing git
2024-06-11 17:17:38,433 DEBUG   HandlerThread:5572 [system_info.py:_probe_git():145] Probing git done
2024-06-11 17:17:38,437 DEBUG   HandlerThread:5572 [system_info.py:probe():200] Probing system done
2024-06-11 17:17:38,437 DEBUG   HandlerThread:5572 [system_monitor.py:probe():223] {'os': 'macOS-14.5-arm64-arm-64bit', 'python': '3.8.18', 'heartbeatAt': '2024-06-11T14:17:38.416498', 'startedAt': '2024-06-11T14:17:37.246548', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/two_d_train.py', 'codePathLocal': 'two_d_train.py', 'codePath': 'two_d_train.py', 'git': {'remote': 'https://github.com/idanv87/deep_attention.git', 'commit': '5878c22234b307cf71b4024ceec474a68d131ae3'}, 'email': 'idanv@campus.technion.ac.il', 'root': '/Users/idanversano/Documents/project_geo_deeponet/deep_attention/src', 'host': 'idans-MacBook-Air.local', 'username': 'idanversano', 'executable': '/Users/idanversano/miniforge3/envs/torch_env/bin/python', 'cpu_count': 8, 'cpu_count_logical': 8, 'cpu_freq': {'current': 3204, 'min': 600, 'max': 3204}, 'cpu_freq_per_core': [{'current': 3204, 'min': 600, 'max': 3204}], 'disk': {'/': {'total': 228.27386474609375, 'used': 9.562911987304688}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 8.0}}
2024-06-11 17:17:38,437 INFO    HandlerThread:5572 [system_monitor.py:probe():224] Finished collecting system info
2024-06-11 17:17:38,437 INFO    HandlerThread:5572 [system_monitor.py:probe():227] Publishing system info
2024-06-11 17:17:38,437 DEBUG   HandlerThread:5572 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2024-06-11 17:17:38,441 ERROR   HandlerThread:5572 [system_info.py:_save_conda():223] Error saving conda packages: [Errno 2] No such file or directory: 'conda'
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/system_info.py", line 216, in _save_conda
    subprocess.call(
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'conda'
2024-06-11 17:17:38,443 DEBUG   HandlerThread:5572 [system_info.py:_save_conda():224] Saving conda packages done
2024-06-11 17:17:38,443 INFO    HandlerThread:5572 [system_monitor.py:probe():229] Finished publishing system info
2024-06-11 17:17:38,448 DEBUG   SenderThread:5572 [sender.py:send():379] send: files
2024-06-11 17:17:38,448 INFO    SenderThread:5572 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2024-06-11 17:17:38,513 ERROR   gpuapple  :5572 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-11 17:17:38,537 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: python_packages
2024-06-11 17:17:38,537 DEBUG   SenderThread:5572 [sender.py:send_request():406] send_request: python_packages
2024-06-11 17:17:38,538 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:17:38,538 DEBUG   SenderThread:5572 [sender.py:send():379] send: telemetry
2024-06-11 17:17:38,538 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: stop_status
2024-06-11 17:17:38,539 DEBUG   SenderThread:5572 [sender.py:send_request():406] send_request: stop_status
2024-06-11 17:17:38,905 INFO    Thread-12 :5572 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240611_171737-jzp58xbj/files/conda-environment.yaml
2024-06-11 17:17:38,905 INFO    Thread-12 :5572 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240611_171737-jzp58xbj/files/output.log
2024-06-11 17:17:38,905 INFO    Thread-12 :5572 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240611_171737-jzp58xbj/files/wandb-metadata.json
2024-06-11 17:17:38,905 INFO    Thread-12 :5572 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240611_171737-jzp58xbj/files/requirements.txt
2024-06-11 17:17:39,208 INFO    wandb-upload_0:5572 [upload_job.py:push():130] Uploaded file /var/folders/tf/xl2_rn496w36wzs_pk18q7vr0000gn/T/tmp9esh5hx_wandb/3vr9scoc-wandb-metadata.json
2024-06-11 17:17:39,544 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:17:40,545 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:17:40,628 ERROR   gpuapple  :5572 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-11 17:17:40,909 INFO    Thread-12 :5572 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240611_171737-jzp58xbj/files/output.log
2024-06-11 17:17:41,550 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:17:42,297 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: status_report
2024-06-11 17:17:42,551 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:17:42,747 ERROR   gpuapple  :5572 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-11 17:17:42,920 INFO    Thread-12 :5572 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240611_171737-jzp58xbj/files/output.log
2024-06-11 17:17:43,556 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:17:44,562 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:17:44,870 ERROR   gpuapple  :5572 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-11 17:17:44,931 INFO    Thread-12 :5572 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240611_171737-jzp58xbj/files/output.log
2024-06-11 17:17:45,566 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:17:46,567 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:17:46,941 INFO    Thread-12 :5572 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240611_171737-jzp58xbj/files/output.log
2024-06-11 17:17:46,985 ERROR   gpuapple  :5572 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-11 17:17:47,317 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: status_report
2024-06-11 17:17:47,572 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:17:48,577 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:17:48,949 INFO    Thread-12 :5572 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240611_171737-jzp58xbj/files/output.log
2024-06-11 17:17:49,109 ERROR   gpuapple  :5572 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-11 17:17:49,582 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:17:50,587 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:17:50,960 INFO    Thread-12 :5572 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240611_171737-jzp58xbj/files/output.log
2024-06-11 17:17:51,231 ERROR   gpuapple  :5572 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-11 17:17:51,589 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:17:52,477 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: status_report
2024-06-11 17:17:52,591 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:17:52,970 INFO    Thread-12 :5572 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240611_171737-jzp58xbj/files/output.log
2024-06-11 17:17:53,352 ERROR   gpuapple  :5572 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-11 17:17:53,542 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: stop_status
2024-06-11 17:17:53,542 DEBUG   SenderThread:5572 [sender.py:send_request():406] send_request: stop_status
2024-06-11 17:17:53,593 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:17:54,598 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:17:54,977 INFO    Thread-12 :5572 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240611_171737-jzp58xbj/files/output.log
2024-06-11 17:17:55,472 ERROR   gpuapple  :5572 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-11 17:17:55,603 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:17:56,608 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:17:56,985 INFO    Thread-12 :5572 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240611_171737-jzp58xbj/files/output.log
2024-06-11 17:17:57,566 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: status_report
2024-06-11 17:17:57,584 ERROR   gpuapple  :5572 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-11 17:17:57,609 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:17:58,613 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:17:58,991 INFO    Thread-12 :5572 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240611_171737-jzp58xbj/files/output.log
2024-06-11 17:17:59,615 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:17:59,705 ERROR   gpuapple  :5572 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-11 17:18:00,620 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:18:01,000 INFO    Thread-12 :5572 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240611_171737-jzp58xbj/files/output.log
2024-06-11 17:18:01,755 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:18:01,828 ERROR   gpuapple  :5572 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-11 17:18:02,007 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: partial_history
2024-06-11 17:18:02,010 DEBUG   SenderThread:5572 [sender.py:send():379] send: history
2024-06-11 17:18:02,010 DEBUG   SenderThread:5572 [sender.py:send_request():406] send_request: summary_record
2024-06-11 17:18:02,011 INFO    SenderThread:5572 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-06-11 17:18:02,633 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: status_report
2024-06-11 17:18:02,672 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:18:03,010 INFO    Thread-12 :5572 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240611_171737-jzp58xbj/files/output.log
2024-06-11 17:18:03,010 INFO    Thread-12 :5572 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240611_171737-jzp58xbj/files/wandb-summary.json
2024-06-11 17:18:03,677 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:18:03,977 ERROR   gpuapple  :5572 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-11 17:18:04,681 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:18:05,021 INFO    Thread-12 :5572 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240611_171737-jzp58xbj/files/output.log
2024-06-11 17:18:05,683 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:18:06,127 ERROR   gpuapple  :5572 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-11 17:18:06,687 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:18:07,028 INFO    Thread-12 :5572 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240611_171737-jzp58xbj/files/output.log
2024-06-11 17:18:07,685 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: status_report
2024-06-11 17:18:07,689 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:18:08,034 INFO    Thread-12 :5572 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240611_171737-jzp58xbj/files/config.yaml
2024-06-11 17:18:08,268 ERROR   gpuapple  :5572 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-11 17:18:08,543 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: stop_status
2024-06-11 17:18:08,544 DEBUG   SenderThread:5572 [sender.py:send_request():406] send_request: stop_status
2024-06-11 17:18:08,694 DEBUG   HandlerThread:5572 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-11 17:18:09,039 INFO    Thread-12 :5572 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240611_171737-jzp58xbj/files/output.log
2024-06-11 17:18:10,328 INFO    cpu       :5572 [interfaces.py:monitor():138] Process cpu has exited.
2024-06-11 17:18:10,328 DEBUG   SystemMonitor:5572 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-06-11 17:18:10,329 DEBUG   SystemMonitor:5572 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-06-11 17:18:10,329 DEBUG   SystemMonitor:5572 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-06-11 17:18:10,330 DEBUG   SenderThread:5572 [sender.py:send():379] send: telemetry
2024-06-11 17:18:10,330 DEBUG   SenderThread:5572 [sender.py:send():379] send: stats
2024-06-11 17:18:10,392 INFO    MainThread:5572 [internal.py:handle_exit():75] Internal process exited
